"use client"

import { useEffect, useState } from "react"
import { ShieldCheck, FileText, AlertTriangle, TrendingDown, MoreVertical, Megaphone, BadgeCheck, Loader2, Download } from "lucide-react"
import { jsPDF } from "jspdf"
import Link from "next/link"

type PlatformData = {
  platform: string
  avgDeficit: number
  workerCount: number
  exploitationScore: number
}

type CityData = {
  city: string
  count: number
}

export default function AnalyticsDashboard() {
  const [platforms, setPlatforms] = useState<PlatformData[]>([])
  const [cities, setCities] = useState<CityData[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function fetchData() {
      try {
        const res = await fetch("/api/index")
        const json = await res.json()
        if (json.index) setPlatforms(json.index)
        if (json.cities) setCities(json.cities)
      } catch (error) {
        console.error("Failed to fetch dashboard data:", error)
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  const exportPDF = () => {
    const doc = new jsPDF()
    const totalSubmissions = platforms.reduce((acc, p) => acc + p.workerCount, 0)
    
    doc.setFontSize(22)
    doc.setFont("helvetica", "bold")
    doc.text("GigShield Worker Exploitation Report", 14, 20)
    
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text(`Generated exactly on: ${new Date().toLocaleString()}`, 14, 30)
    doc.text(`Total Submissions: ${totalSubmissions}`, 14, 38)
    
    doc.setFont("helvetica", "bold")
    doc.text("Platform", 14, 55)
    doc.text("Avg. Monthly Deficit", 70, 55)
    doc.text("Submissions", 140, 55)
    
    doc.setFont("helvetica", "normal")
    let yPos = 65
    platforms.forEach((p) => {
      doc.text(p.platform, 14, yPos)
      doc.text(`Rs. ${p.avgDeficit.toLocaleString('en-IN')}`, 70, yPos)
      doc.text(p.workerCount.toString(), 140, yPos)
      yPos += 10
    })
    
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(10)
    doc.text("Generated by GigShield — Telangana Labour Dept Tool", 14, 280)
    
    doc.save("GigShield-Exploitation-Report.pdf")
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0e0e0e] flex items-center justify-center pb-24">
        <Loader2 className="w-8 h-8 text-neutral-500 animate-spin" />
      </div>
    )
  }

  const totalSubmissions = platforms.reduce((acc, p) => acc + p.workerCount, 0)
  const sortedPlatforms = [...platforms].sort((a, b) => b.avgDeficit - a.avgDeficit)
  const mostExploitative = sortedPlatforms[0]?.platform || "N/A"
  
  const totalDeficit = platforms.reduce((acc, p) => acc + (p.avgDeficit * p.workerCount), 0)
  const globalAvgDeficit = totalSubmissions > 0 ? Math.round(totalDeficit / totalSubmissions) : 0

  return (
    <div className="min-h-screen bg-[#0e0e0e] text-white p-4 md:p-8 font-sans pb-24 selection:bg-green-500/30">
      <div className="max-w-md md:max-w-4xl mx-auto space-y-6">
        
        {/* HEADER */}
        <header className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-8">
          <div>
            <p className="text-[11px] font-bold tracking-[0.2em] text-neutral-500 uppercase mb-2">System Overview</p>
            <h1 className="text-3xl md:text-5xl font-black tracking-tight text-white flex items-center gap-3">
              Analytics Dashboard
            </h1>
          </div>
          <button onClick={exportPDF} className="flex items-center gap-2 text-sm font-bold bg-[#1c1b1b] border border-neutral-800 hover:bg-[#201f1f] transition-colors py-3 px-5 rounded-full text-neutral-300 w-full md:w-auto justify-center">
            <Download className="w-4 h-4" />
            Export Report
          </button>
        </header>

        {/* TOP STATS ROW */}
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-[#131313] border border-neutral-800/60 rounded-3xl p-6 flex flex-col justify-between h-36">
            <div className="flex justify-between items-start">
              <FileText className="w-5 h-5 text-[#3ce36a]" />
              <div className="bg-[#003912] text-[#3fe56c] text-[10px] font-bold px-2 py-0.5 rounded-full border border-[#00c853]/30">+12%</div>
            </div>
            <div>
              <p className="text-xs font-medium text-neutral-500 mb-1">Total Submissions</p>
              <p className="text-2xl font-black text-white">{totalSubmissions.toLocaleString()}</p>
            </div>
          </div>

          <div className="bg-[#131313] border border-neutral-800/60 rounded-3xl p-6 flex flex-col justify-between h-36">
            <div className="flex justify-between items-start">
              <AlertTriangle className="w-5 h-5 text-[#2fb9f9]" />
            </div>
            <div>
              <p className="text-xs font-medium text-neutral-500 mb-1">Top Exploitative</p>
              <p className="text-2xl font-black text-white truncate">{mostExploitative}</p>
            </div>
          </div>
        </div>

        {/* AVERAGE DEFICIT CARD */}
        <div className="bg-gradient-to-br from-[#2a1313] to-[#131313] border border-[#ff4c4c]/20 rounded-[32px] p-8 md:p-10 relative overflow-hidden group">
          <TrendingDown className="absolute right-6 top-6 w-32 h-32 text-[#ff4c4c]/10 -rotate-12 group-hover:scale-110 transition-transform duration-700" />
          <div className="relative z-10">
            <div className="flex items-center gap-2 mb-4">
              <TrendingDown className="w-5 h-5 text-[#ff4c4c]" />
              <span className="text-xs font-bold tracking-widest text-[#ff4c4c] uppercase">Average Deficit</span>
            </div>
            <h2 className="text-5xl md:text-7xl font-black text-[#ff7162] tracking-tighter mb-2">
              -₹{globalAvgDeficit.toLocaleString('en-IN')}<span className="text-2xl md:text-3xl text-[#ff7162]/60 font-bold">/mo</span>
            </h2>
            <p className="text-sm font-medium text-neutral-400">Monthly gap across all verified platforms</p>
          </div>
        </div>

        {/* UNDERPAYMENT TREND GRID */}
        <div className="bg-[#131313] border border-neutral-800/60 rounded-[32px] p-6 md:p-8">
          <div className="flex justify-between items-start mb-8">
            <div>
              <h3 className="text-xl font-bold text-white mb-1">Underpayment Trend</h3>
              <p className="text-xs font-medium text-neutral-500">Platform comparison (all time)</p>
            </div>
            <MoreVertical className="w-5 h-5 text-neutral-600" />
          </div>

          <div className="space-y-6">
            {sortedPlatforms.map((platform) => {
              // Calculate width based on max deficit
              const maxDeficit = Math.max(...platforms.map(p => p.avgDeficit)) || 1
              const percentage = Math.min(100, Math.max(5, (platform.avgDeficit / maxDeficit) * 100))
              const isPositive = platform.avgDeficit <= 0
              
              return (
                <div key={platform.platform} className="space-y-2">
                  <div className="flex justify-between text-sm font-bold">
                    <span className="text-neutral-200">{platform.platform}</span>
                    <span className={isPositive ? "text-[#3ce36a]" : "text-[#ff7162]"}>
                      {isPositive ? '+' : '-'}₹{Math.abs(platform.avgDeficit).toLocaleString('en-IN')}/mo
                    </span>
                  </div>
                  <div className="h-3 w-full bg-[#1c1b1b] rounded-full overflow-hidden flex">
                    <div 
                      className={`h-full rounded-full transition-all duration-1000 ${isPositive ? 'bg-[#3ce36a]' : 'bg-[#ff7162]'}`} 
                      style={{ width: `${percentage}%` }}
                    />
                  </div>
                </div>
              )
            })}
          </div>
        </div>

        {/* CRITICAL INSIGHTS */}
        <div className="space-y-4">
          <h3 className="text-xl font-bold text-white mb-4 mt-8 px-2">Critical Insights</h3>
          
          <div className="bg-[#131313] border border-[#ff4c4c]/20 rounded-2xl p-5 flex gap-4 items-start relative overflow-hidden">
            <div className="absolute left-0 top-0 bottom-0 w-1 bg-[#ff4c4c]"></div>
            <div className="w-10 h-10 rounded-full bg-[#ff4c4c]/10 flex justify-center items-center shrink-0 border border-[#ff4c4c]/20">
              <Megaphone className="w-4 h-4 text-[#ff4c4c]" />
            </div>
            <div>
              <h4 className="font-bold text-white text-sm mb-1">New Policy Alert</h4>
              <p className="text-xs text-neutral-400 leading-relaxed font-medium">Platforms updated gig algorithms in your region. Expected deficit increase: 8%.</p>
            </div>
          </div>

          <div className="bg-[#131313] border border-[#3ce36a]/20 rounded-2xl p-5 flex gap-4 items-start relative overflow-hidden">
            <div className="absolute left-0 top-0 bottom-0 w-1 bg-[#3ce36a]"></div>
            <div className="w-10 h-10 rounded-full bg-[#3ce36a]/10 flex justify-center items-center shrink-0 border border-[#3ce36a]/20">
              <BadgeCheck className="w-4 h-4 text-[#3ce36a]" />
            </div>
            <div>
              <h4 className="font-bold text-white text-sm mb-1">Fair Pay Achievement</h4>
              <p className="text-xs text-neutral-400 leading-relaxed font-medium">Local Urban Company batches currently meeting ethical standards.</p>
            </div>
          </div>
        </div>

      </div>
    </div>
  )
}
