"use client"

import { useEffect, useState } from "react"
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts"
import { jsPDF } from "jspdf"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Download, AlertTriangle, Users, TrendingDown, Loader2 } from "lucide-react"

type PlatformData = {
  name: string
  avgDeficit: number
  count: number
  exploitationScore: number
}

type CityData = {
  city: string
  count: number
}

export default function LabourDashboard() {
  const [platforms, setPlatforms] = useState<PlatformData[]>([])
  const [cities, setCities] = useState<CityData[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function fetchData() {
      try {
        const res = await fetch("/api/index")
        const json = await res.json()
        
        // Handle various possible response structures gracefully
        const fetchedPlatforms: PlatformData[] = json.index?.map((item: any) => ({
          name: item.platform,
          avgDeficit: item.avgDeficit,
          count: item.workerCount,
          exploitationScore: item.exploitationScore,
        })) || json.platforms || []

        setPlatforms(fetchedPlatforms)
        
        if (json.cities && Array.isArray(json.cities)) {
          setCities(json.cities)
        } else {
          // Fallback or mock for city data if api doesn't provide it yet
          if (fetchedPlatforms.length > 0) {
            setCities([{ city: "Hyderabad", count: fetchedPlatforms.reduce((sum: number, p: any) => sum + p.count, 0) }])
          }
        }
      } catch (error) {
        console.error("Failed to fetch dashboard data:", error)
      } finally {
        setLoading(false)
      }
    }
    fetchData()
  }, [])

  const exportPDF = () => {
    const doc = new jsPDF()
    const totalSubmissions = platforms.reduce((acc, p) => acc + p.count, 0)
    
    // Title
    doc.setFontSize(22)
    doc.setFont("helvetica", "bold")
    doc.text("GigShield Worker Exploitation Report", 14, 20)
    
    // Meta
    doc.setFontSize(11)
    doc.setFont("helvetica", "normal")
    doc.text(`Generated exactly on: ${new Date().toLocaleString()}`, 14, 30)
    doc.text(`Total Submissions: ${totalSubmissions}`, 14, 38)
    
    // Table Header
    doc.setFont("helvetica", "bold")
    doc.text("Platform", 14, 55)
    doc.text("Avg. Monthly Deficit", 70, 55)
    doc.text("Submissions", 140, 55)
    
    // Table Rows
    doc.setFont("helvetica", "normal")
    let yPos = 65
    platforms.forEach((p) => {
      doc.text(p.name, 14, yPos)
      doc.text(`Rs. ${p.avgDeficit.toLocaleString('en-IN')}`, 70, yPos)
      doc.text(p.count.toString(), 140, yPos)
      yPos += 10
    })
    
    // Footer
    doc.setTextColor(100, 100, 100)
    doc.setFontSize(10)
    doc.text("Generated by GigShield — Telangana Labour Dept Tool", 14, 280)
    
    doc.save("GigShield-Exploitation-Report.pdf")
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] flex items-center justify-center">
        <Loader2 className="w-8 h-8 text-neutral-500 animate-spin" />
      </div>
    )
  }

  if (platforms.length === 0) {
    return (
      <div className="min-h-screen bg-[#0a0a0a] text-white flex flex-col items-center justify-center p-4">
        <h1 className="text-3xl font-bold mb-4">Labour Dashboard</h1>
        <p className="text-neutral-400">No submissions yet. Share GigShield with workers to start collecting data.</p>
      </div>
    )
  }

  const totalSubmissions = platforms.reduce((acc, p) => acc + p.count, 0)
  const sortedPlatforms = [...platforms].sort((a, b) => b.avgDeficit - a.avgDeficit)
  const mostExploitative = sortedPlatforms[0]?.name || "N/A"
  
  const totalDeficit = platforms.reduce((acc, p) => acc + (p.avgDeficit * p.count), 0)
  const globalAvgDeficit = totalSubmissions > 0 ? Math.round(totalDeficit / totalSubmissions) : 0

  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white p-4 md:p-8 font-sans selection:bg-red-500/30">
      <div className="max-w-7xl mx-auto space-y-8">
        
        {/* HEADER */}
        <header className="flex flex-col md:flex-row md:items-start justify-between gap-4 border-b border-neutral-800 pb-6 mt-4">
          <div className="space-y-2">
            <div className="flex items-center gap-3 mb-1">
              <h1 className="text-3xl font-black tracking-tight text-white">Labour Dashboard</h1>
              <Badge className="bg-red-500/10 text-red-500 border border-red-500/20 shadow-none text-xs uppercase tracking-wider">
                Official Use Only
              </Badge>
            </div>
            <p className="text-neutral-400">
              Live exploitation data from anonymous worker reports
            </p>
          </div>
          
          <div className="flex justify-end pt-2 md:pt-0">
            <Button 
              onClick={exportPDF} 
              className="bg-white text-black hover:bg-neutral-200 font-bold px-6 shadow-none"
            >
              <Download className="mr-2 h-4 w-4" />
              Export PDF Report
            </Button>
          </div>
        </header>

        {/* STATS ROW */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="bg-neutral-900 border-neutral-800 shadow-none">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-neutral-400 uppercase tracking-wider">
                Total Submissions
              </CardTitle>
              <Users className="w-5 h-5 text-neutral-500" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-white">{totalSubmissions}</div>
            </CardContent>
          </Card>

          <Card className="bg-neutral-900 border-neutral-800 shadow-none">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-neutral-400 uppercase tracking-wider">
                Most Exploitative
              </CardTitle>
              <AlertTriangle className="w-5 h-5 text-red-500" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-red-500">{mostExploitative}</div>
            </CardContent>
          </Card>

          <Card className="bg-neutral-900 border-neutral-800 shadow-none">
            <CardHeader className="flex flex-row items-center justify-between pb-2">
              <CardTitle className="text-sm font-medium text-neutral-400 uppercase tracking-wider">
                Avg Monthly Deficit
              </CardTitle>
              <TrendingDown className="w-5 h-5 text-neutral-500" />
            </CardHeader>
            <CardContent>
              <div className="text-3xl font-bold text-white">₹{globalAvgDeficit.toLocaleString('en-IN')}</div>
              <p className="text-xs text-neutral-500 mt-1 uppercase tracking-wider">Across all submissions</p>
            </CardContent>
          </Card>
        </div>

        {/* CHARTS ROW */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          
          <Card className="bg-neutral-900 border-neutral-800 shadow-none">
            <CardHeader>
              <CardTitle className="text-lg text-white font-medium">Average Monthly Deficit by Platform</CardTitle>
            </CardHeader>
            <CardContent className="h-80 pt-4">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={sortedPlatforms} margin={{ top: 10, right: 10, left: 0, bottom: 20 }}>
                  <XAxis 
                    dataKey="name" 
                    stroke="#525252" 
                    tick={{ fill: "#a3a3a3", fontSize: 12 }} 
                    axisLine={false} 
                    tickLine={false} 
                  />
                  <YAxis 
                    stroke="#525252" 
                    tick={{ fill: "#a3a3a3", fontSize: 12 }} 
                    axisLine={false} 
                    tickLine={false} 
                    tickFormatter={(val) => `₹${val}`}
                  />
                  <Tooltip 
                    cursor={{ fill: '#171717' }}
                    contentStyle={{ backgroundColor: '#0a0a0a', border: '1px solid #262626', borderRadius: '8px' }}
                    formatter={(val: any) => [`₹${Number(val).toLocaleString('en-IN')}`, 'Avg Deficit']}
                  />
                  <Bar dataKey="avgDeficit" fill="#ef4444" radius={[4, 4, 0, 0]} maxBarSize={60} />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

          <Card className="bg-neutral-900 border-neutral-800 shadow-none">
            <CardHeader>
              <CardTitle className="text-lg text-white font-medium">Submissions by City</CardTitle>
            </CardHeader>
            <CardContent className="h-80 pt-4">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={cities} margin={{ top: 10, right: 10, left: 0, bottom: 20 }}>
                  <XAxis 
                    dataKey="city" 
                    stroke="#525252" 
                    tick={{ fill: "#a3a3a3", fontSize: 12 }} 
                    axisLine={false} 
                    tickLine={false} 
                  />
                  <YAxis 
                    stroke="#525252" 
                    tick={{ fill: "#a3a3a3", fontSize: 12 }} 
                    axisLine={false} 
                    tickLine={false} 
                  />
                  <Tooltip 
                    cursor={{ fill: '#171717' }}
                    contentStyle={{ backgroundColor: '#0a0a0a', border: '1px solid #262626', borderRadius: '8px' }}
                    formatter={(val: any) => [val, 'Submissions']}
                  />
                  <Bar dataKey="count" fill="#f97316" radius={[4, 4, 0, 0]} maxBarSize={60} />
                </BarChart>
              </ResponsiveContainer>
            </CardContent>
          </Card>

        </div>
      </div>
    </div>
  )
}
